### PR TITLE
Update marked and a few more changes

### PR DESCRIPTION
**Pull request by zimme**
* Update marked to 0.3.5
* Cleanup export code
* Drop support for Meteor < 1.0

### CODE REVIEW

**Comment by gadicc** [comment]
hey, @zimme!  thanks for the PR.

I have a few comments:

* I had to make the version v0.3.5_1 since there was already an older mis-published v0.3.5 (not using marked v0.3.5).

* Re the export code, I didn't test, but I'm pretty sure with that change, upstream marked with pollute the global namespace, which we want to avoid (unless the app itself imports the marked package).

* If there's no reason to drop old Meteor version support, I'd rather just keep it in.

Having said all that, I just published v0.3.5_1.  Hope you agree with my comments.

**Comment by zimme** [comment]
How about this code in the `post-marked.js` file or as `export.js`.
```js
async = this.async;
try {
  delete this.async;
} catch (e) { }
```

**Comment by zimme** [comment]
Also, please tag your releases =)

**Comment by gadicc** [comment]
Ugh :(  Yeah, I miss `mrt`.  I tagged the latest release.  And guess I'll make a script to handle future publish+tag, unless you're aware of something already?

Back to post-marked.js; how is that any better than what we have now?  I prefer marked to load realizing that it's being loaded as a module, instead of loading in global namespace and deleting afterwards.  Is there something problematic for you in the current implementation?

**Comment by zimme** [comment]
Nah it works, I was just thinking it might be nice to have the exporting logic in one file.

**Comment by gadicc** [comment]
Oh, yeah... I'm hoping things will get more interesting when everyone moves towards ES6 modules (with transpilation for AMD, CommonJS, etc) and Meteor adds ES6 module support to packages or we just use [rocket:module](https://github.com/meteor-rocket/module).

**Comment by zimme** [comment]
Well, closing this as the marked update is done at least =)

**Pull request closed without merging**
